### PR TITLE
Kahuna phone credential

### PR DESCRIPTION
**Pull request by sashikahuna**
@hankim813 - please review... we are going to support a new credential for "phone" called "mobile_number", so wanted to pass this along from Segment if it's there. I noticed "phone" was part of Segment's "traits", so was grabbing it from there... don't think "identity" has a helper method to grab that value... feel free to suggest better ways to do this. thanks!

### CODE REVIEW

**Comment by hankim813** [comment]
@sashikahuna thanks for the PR!

The `identity` parameter actually does have a helper method for this trait :)

You can use `.identity.phone()` instead of passing in `traits` everywhere. The `.phone()` will look up `traits.phone` under the hood!

Another future note, if you are unsure if a "helper" method exists, you can easily retrieve any trait/property/context value by using `.proxy()`.

So in this example, you can also alternatively do `identity.proxy('traits.phone')`

**Comment by sashikahuna** [comment]
@hankim813  thanks! yes, you're right... I actually thought to check .proxy() but decided instead to pass the traits around, which wasn't good :) I cleaned it up, however I noticed that the identify and track don't have .phone() available, is that correct? so, instead I had to use .proxy('traits.phone') to get it... let me know if can optimize better. thanks again.

**Comment by sashikahuna** [comment]
@hankim813 - friendly reminder to review the latest changes, thanks!

**Comment by hankim813** [comment]
@sashikahuna done -- will deploy tomorrow morning

**Comment by sashikahuna** [comment]
Thanks so much @hankim813 !

**Comment by hankim813** [comment]
@sashikahuna deployed!

**Pull request merged**
